CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL,
	password VARCHAR(12) NOT NULL,
	active BOOLEAN NOT NULL DEFAULT FALSE,
	created_at TIMESTAMP NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS pre_registration (
	id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL,
	hash TEXT NOT NULL,
	expiration_date TIMESTAMP NOT NULL,
	CONSTRAINT fk_user_id
	    FOREIGN KEY (user_id) REFERENCES users(id)
);