CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL,
	password VARCHAR(12) NOT NULL,
	active BOOLEAN NOT NULL DEFAULT FALSE,
	date_birth DATE NULL,
	created_at TIMESTAMP NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS pre_registration (
	id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL,
	activation_key UUID NOT NULL,
	expiration_date DATE NOT NULL,
	active BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE pre_registration ADD CONSTRAINT fk_user_id
FOREIGN KEY (user_id) REFERENCES users(id);