server:
  port: 8080
spring:
  application:
    name: gestao-usuario-api
  datasource:
    url: jdbc:h2:mem:usuario_db
    driverClassName: org.h2.Driver
    initialization-mode: always
    username: sa
    password:
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
springdoc:
  api-docs.path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
