server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/usuario_db
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: never
  jpa:
    defer-datasource-initialization: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

security:
  public-endpoints:
    - /auth/**
  disable-security-headers: false
  jwt:
    secret: ${JWT_SECRET}
    expirationMS: ${JWT_EXPIRATION_MS:3600000}