spring.application.name=gestao-usuario-api

#spring.datasource.url=jdbc:postgresql://localhost:5432/DBGestaoUsuario
#spring.datasource.username=admin
#spring.datasource.password=admin
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= update
