spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:usuario_db
  h2:
    console:
      enabled: true
      path: /h2-console
security:
  public-endpoints:
    - /swagger-ui.html
    - /v3/api-docs/**
    - /swagger-ui/**
    - /h2-console/**
  disable-security-headers: true
